### ISSUE TITLE
Fail to grab a books

### ISSUE THREAD

**Issue by ranrinc** [luk6xff/Packt-Publishing-Free-Learning#135] opened 2019-03-08 14:36 UTC
Hi there,

Its seems that the script failed to grab a books even though its say complete.
So its failed to find the books that suppose to be grab already.

Upon manually grab and run the script again its found the right books and download..

Maybe Packt change the HTML again?

<img width="651" alt="error" src="https://user-images.githubusercontent.com/15801696/54034812-69853100-41ea-11e9-8597-b10918ad177c.png">

**Comment by ranrinc** [comment] 2019-03-09 04:30
I test it again today and confirm that the current scrip unable to grab the new books. Its saya getting you book data and upon successfully fetched its fail to do it so it end up with not founding the current books.

**Comment by stashme** [comment] 2019-03-10 10:38
I had this problem too - seems there is a delay at Packt between claiming an ebook and the availability to download it. 
I applied a quick'n'dirty fix by adding a time.sleep before "ebook.download_books" in packtPublishingFreeEbook.py, but there might be a better way to deal with this.

**Comment by mjenczmyk** [comment] 2019-03-11 09:04
I've never encountered this problem after script modification in January (I've a cron job set up to run everyday). If you say it happens to you we can pass `product_id` (an ID of the claimed) product directly to `download_books` instead of `titles` parameter, we will see whether it helps and it's more elegant solution anyway. I'll make a pull request.

Does the problem you're describing happens often? Was it a single time or does it happen regularly?

**Comment by ranrinc** [comment] 2019-03-11 09:30
@mjenczmyk I my ubuntu it fail to retrieve the book every time. No luck so far. The only way to grab the books is manually and then run the scripts, then it will be able to found the book and download. So would like to get some assistant on this issue

**Comment by mjenczmyk** [comment] 2019-03-12 08:46
Try installing the script using `pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@id`. If that won't help what is the output of `pip freeze` from the virtualenv? What is the version you're using currently?

**Comment by mjenczmyk** [comment] 2019-03-17 07:05
I've merged the pull request (it won't break anything, but it may not have resolved your problem).

**Comment by mjenczmyk** [comment] 2019-03-21 15:35
Any news, did it help (I don't think it should've helped)?

**Comment by stashme** [comment] 2019-03-25 08:23
I have dropped my local patch "time.sleep(60)" and checked out master (7c0b264), unfortunately it did not work:

> 2019-03-25 01:00:04,855 - api - [INFO] - JWT token has been fetched successfully!
> 2019-03-25 01:00:04,856 - packtPublishingFreeEbook - [INFO] - Start grabbing ebook...
> 2019-03-25 01:00:05,163 - packtPublishingFreeEbook - [INFO] - Started solving ReCAPTCHA on Packt Free Learning website...
> 2019-03-25 01:00:06,694 - utils.anticaptcha - [INFO] - Waiting for completion of the xxx task...
> 2019-03-25 01:00:49,096 - utils.anticaptcha - [SUCCESS] - Solution found for xxx task.
> 2019-03-25 01:00:49,446 - packtPublishingFreeEbook - [INFO] - A new Packt Free Learning ebook "Mastering Kubernetes" has been grabbed!
> 2019-03-25 01:00:49,513 - packtPublishingFreeEbook - [INFO] - Title: "Mastering Kubernetes"
> 2019-03-25 01:00:49,517 - packtPublishingFreeEbook - [INFO] - Downloading ebook: "Mastering Kubernetes" in epub format...
> 2019-03-25 01:00:49,963 - packtPublishingFreeEbook - [ERROR] - Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> 2019-03-25 01:00:49,964 - packtPublishingFreeEbook - [INFO] - Title: "Mastering Kubernetes"
> 2019-03-25 01:00:49,965 - packtPublishingFreeEbook - [INFO] - Downloading ebook: "Mastering Kubernetes" in pdf format...
> 2019-03-25 01:00:50,264 - packtPublishingFreeEbook - [ERROR] - Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> 2019-03-25 01:00:50,264 - packtPublishingFreeEbook - [INFO] - 0 ebooks have been downloaded!
> 2019-03-25 01:00:50,265 - packtPublishingFreeEbook - [SUCCESS] - Good, looks like all went well! :-)

Any idea? Thanks.

**Comment by mjenczmyk** [comment] 2019-03-25 17:00
Did you ran `pip install -e '.[dev]'` after checking out? What command did you ran in the command line?

**Comment by stashme** [comment] 2019-03-26 20:06
Yes, I did run `pip install -e '.[dev]`. I am running `packt-cli -gd` via cron

**Comment by mjenczmyk** [comment] 2019-04-09 10:03
I've no idea what's the problem. Sorry, I'm afraid I'm unable to help with this.

**Comment by VictorJ76** [comment] 2019-07-25 12:50
Yes it looks like good now. I'll see in the future.

Thank you mjenczmyk ;)

**Comment by mjenczmyk** [comment] 2019-08-21 08:23
It's a duplicate of #162, I'll try to resolve both issues soon.

**Comment by mjenczmyk** [comment] 2019-09-05 13:32
Resolved by #166.

**Closed by mjenczmyk** 2019-09-05 13:32 UTC
