### ISSUE TITLE
login to packt issue

### ISSUE THREAD

**Issue by alfiqmiq** [luk6xff/Packt-Publishing-Free-Learning#174] opened 2019-11-21 11:36 UTC
from a few days...

packt-cli -gd
[ERROR] - Fetching JWT token failed!
[INFO] - Start grabbing ebook...
[ERROR] - Exception occurred 'NoneType' object is not iterable

as i think is new packt double check issue (config for connection is ok)

![image](https://user-images.githubusercontent.com/9507245/69334637-786a2180-0c5b-11ea-8021-c471226c8934.png)

**Comment by mjenczmyk** [comment] 2019-11-21 19:28
Isn't that duplicate of #169?

**Comment by mjenczmyk** [comment] 2019-12-17 07:29
I'm assuming it is - in other case we can reopen the issue.

**Closed by mjenczmyk** 2019-12-17 07:29 UTC
